// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVDHLL6bJ7uI4vSDXaJNwzCCF0irNQ8xM',
    appId: '1:302827454952:web:b860283bc67a6afa6ca45d',
    messagingSenderId: '302827454952',
    projectId: 'fooddeliveryapp-87282',
    authDomain: 'fooddeliveryapp-87282.firebaseapp.com',
    storageBucket: 'fooddeliveryapp-87282.firebasestorage.app',
    measurementId: 'G-4Q6NC8WZXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrcei2XeILxtDgV55SObPb1M6ZI5TxbWs',
    appId: '1:302827454952:android:63b5af7108422afc6ca45d',
    messagingSenderId: '302827454952',
    projectId: 'fooddeliveryapp-87282',
    storageBucket: 'fooddeliveryapp-87282.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlex4UvFbUFLNO8rpfVOmGsmvxvGwb7bs',
    appId: '1:302827454952:ios:f439e2ebf32675676ca45d',
    messagingSenderId: '302827454952',
    projectId: 'fooddeliveryapp-87282',
    storageBucket: 'fooddeliveryapp-87282.firebasestorage.app',
    iosBundleId: 'com.example.fooddeliveryapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlex4UvFbUFLNO8rpfVOmGsmvxvGwb7bs',
    appId: '1:302827454952:ios:f439e2ebf32675676ca45d',
    messagingSenderId: '302827454952',
    projectId: 'fooddeliveryapp-87282',
    storageBucket: 'fooddeliveryapp-87282.firebasestorage.app',
    iosBundleId: 'com.example.fooddeliveryapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVDHLL6bJ7uI4vSDXaJNwzCCF0irNQ8xM',
    appId: '1:302827454952:web:16c10843664342476ca45d',
    messagingSenderId: '302827454952',
    projectId: 'fooddeliveryapp-87282',
    authDomain: 'fooddeliveryapp-87282.firebaseapp.com',
    storageBucket: 'fooddeliveryapp-87282.firebasestorage.app',
    measurementId: 'G-111R0FNQW6',
  );
}
